version: '3.9'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
      # - POSTGRES_HOST=${POSTGRES_DB}
      - POSTGRES_HOST=postgres
    networks:
      - custom-network
    # command: npm run start:dev
  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: ./database/Dockerfile
    restart: unless-stopped
    # command: postgres -c logging_collector=on
    env_file:
      - .env
    environment:
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - POSTGRES_DB:${POSTGRES_DB}
      - PGDATA:/var/lib/postgresql/data
      # - PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pg_data:/var/lib/postgresql/data
      # - pg_data:/var/lib/postgresql/data/pgdata
    networks:
      - custom-network
    # host: 
    #   - postgres
volumes: 
  pg_data:
networks:
    custom-network:
      name: custom-network
      driver: bridge 
