version: '3.9'
services:
  app:
    container_name: app
    build: .
      # context: .
      # dockerfile: ./Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
    networks:
      - custom-network
    # command: npm run start:dev
  postgres:
    container_name: postgres
    # image: postgres:latest 
    build:
      context: .
      dockerfile: ./database/Dockerfile
    restart: unless-stopped
    # command: postgres -c logging_collector=on
    # command:
      # - sleep 5 #give the service some time to start
      # - psql -U postgres -d test
      # - psql -U postgres -d test -h db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      # - POSTGRES_PORT=${POSTGRES_PORT}
      # - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
      # - PGDATA={PG_DATA}
    ports:
      - 5432:5432
      # - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - custom-network
volumes: 
  db:
networks:
    custom-network:
      name: custom-network
      driver: bridge 
